### ISSUE TITLE
[1.12] Crash with villager during tooltip

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/SBM-BaggableMobs#2]
https://paste.dimdev.org/goveyoyoba.mccrash

``` 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.getCareer(VillagerRegistry.java:229)
    at com.builtbroken.baggablemobs.lib.BaggableMobsUtil.getCapturedVillagerProfession(BaggableMobsUtil.java:110)
    at com.builtbroken.baggablemobs.content.ItemMobBag.addInformation(ItemMobBag.java:78)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707)
```

**Comment by Sunconure11** [comment]
https://minecraft.curseforge.com/projects/blue-skies

This mod may have some role.

**Comment by Sunconure11** [comment]
The issue is related to a duplicate stat ID. I'm searching for the mod now.
